### ISSUE TITLE
Overwrite Table Not Working Correctly

### ISSUE THREAD

**Issue by nathansahelijo** [campbio/musicatk#32]
@achevali 
The "overwrite" parameter of the build_standard_table function does not work as expected. Instead of overwriting the existing table, it adds another table with the same name. Please note if you have an existing musica "View" tab (View(musica)) open before attempting to overwrite the table you will have to close it in order for it to update.

`data(musica);
build_standard_table(musica, g, "SBS96", overwrite = T);
View(musica@count_tables)`

**Comment by achevali** [comment]
Good catch, I'm testing out a fix for indels which is in the code currently, but I haven't settled on a favorite way to handle this.

**Comment by achevali** [comment]
@nathansahelijo Should be fixed, try pulling master and let me know if it works properly now.

**Comment by nathansahelijo** [comment]
Quick fix. Looks to be working as expected now.
