### ISSUE TITLE
Encoding issue in plot_ functions

### ISSUE THREAD

**Issue by Acare** [campbio/musicatk#41]
Hello,
I think there is a problem with encoding in plotting functions such as `plot_signatures()`, `plot_exposures()`, etc...
Every label/text in ggplot2 images is printed as blocks of four numbers.
I'm using `musicatk` v1.0.0 with R 4.0.5 and Bioconductor v3.12 on a Ubuntu 20.04.2 machine.
I noticed the same issue in the package vignette.
Best regards,

Andrea

**Comment by joshua-d-campbell** [comment]
Hi @Acare, thanks for the heads up. It looks like this is an issue with accessing the font "Courier" on Ubuntu. We will try some of the following solutions:

https://r.789695.n4.nabble.com/Monospaced-font-not-shown-correctly-Xubuntu-20-04-td4767420.html

In the meantime, you should be able to get around this by changing the family font in the ggplot object like this:

```
p <- plot_exposures(result)
library(ggplot2)
p <- p + theme(text = element_text(family = "Courier New"))
p
```

If "Courier New" does not work, you can go back to the default, "Helvetica".
